apiVersion: v1
kind: Service
metadata:
  name: app-examinator-service
  namespace: challenges-demo
spec:
  selector:
    name: examinator
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-config-server-service
  namespace: challenges-demo
spec:
  selector:
    name: config-server
  ports:
    - port: 8080
      targetPort: 8080